### ISSUE TITLE
Problem Login

### ISSUE THREAD

**Issue by Frencisis** [XternA/honeygain-reward#2]
Hi, i've created the docket on my qnap NAS, but the log return the error you can see into the image below.

I've added the Ambient Variable
EMAIL
PASSWORD
as you described

Could you help me?

![honeygain_pot](https://github.com/user-attachments/assets/312d0b3c-eeb4-4321-b74f-d140bc06bd35)

![2024-11-12 07_57_11-Nas - TeamViewer](https://github.com/user-attachments/assets/253392b2-fa1a-4b10-9d17-6c94971838a4)

Thanks

**Comment by XternA** [comment]
Could you kindly share your QNAP hardware spec please?

The container basically has to spin up a chrome browser to automate to the website, but from the looks of it, it seems like the browser was having issue trying to load. This is usually the case when device hardware is at a constraint hence I want to get a better understanding of your NAS hardware.

**Comment by Frencisis** [comment]
Thanks for your reply,
this are the spec hardware of my NAS
QNAP TS-228A
Realtek RTD1295 4-core 1,4GHz
ARM 64-bit
DDR4 1 GB, not expandable

Thanks again for the support

**Comment by XternA** [comment]
Thanks for providing the specs. I suspect the issue is due to the limited amount of RAM that's causing the issue here.

Could you check what's your total RAM usage?

If you've not deployed the Honeygain Pot container via [**IGM**](https://github.com/XternA/income-generator) which has a resource limit applied to it and allows you to adjust it, then try to add a resource constraint to the the app.

For example, you can add the CPU and memory constraint as follow when deploying:

```markdown
# These values is the bare minimum you can set for the container to function properly.
  - cpu=0.8
  - mem_limit=350m
```

**Via CLI**
```markdown
docker run -d --restart unless-stopped --name honeygain-pot \
  -e EMAIL=$HONEYGAIN_EMAIL \
  -e PASSWORD=$HONEYGAIN_PASSWORD \
  --cpus="0.8" \
  --memory="350m" \
  ghcr.io/xterna/honeygain-pot
```

**Via Compose**
```yml
services:
  honeygain-pot:
    container_name: honeygain-pot
    image: xterna/honeygain-pot
    restart: unless-stopped
    environment:
      - EMAIL=$EMAIL
      - PASSWORD=$PASSWORD
    dns:
      - 1.1.1.1
      - 8.8.8.8
    cpus: 0.8
    mem_limit: 350
    mem_reservation: 160
    depends_on:
      - honeygain
```

See if using the resource constraint would work. If it doesn't then unfortunately there isn't enough resource to run Honeygain Pot on your NAS due to resource limit. Alternatively if you have a Raspberry Pi 3 Model B+ (64-bit) or RPI 4, you can run on that.

I've also just pushed a new update so try pulling that one down and giving it a try also.
